'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';
const inter = Inter({ subsets: ['latin'] });
import SidebarAdmin from '@/components/sidebarAdmin';
import Sidebar from '@/components/sidebar';
import { usePathname } from 'next/navigation';
import { useEffect, useState } from 'react';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [pathChk, setPathChk] = useState(true);

  useEffect(() => {
    if (
      pathname === '/auth/signin' ||
      pathname === '/auth/signup' ||
      pathname === '/auth/admin-signup' ||
      pathname === '/auth/admin-signin'
    ) {
      setPathChk(false);
    } else if (pathname === '/notfound') {
      setPathChk(false);
    } else {
      setPathChk(true);
    }
  }, [pathname]);

  const isAdmin: boolean = JSON.parse(
    localStorage.getItem('isAdmin') || 'false'
  );
  console.log('side', isAdmin);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider className="w-full flex">
          {pathChk && isAdmin == true && <SidebarAdmin />}
          {pathChk && isAdmin == false && <Sidebar />}
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
